"""add country column to address

Revision ID: 2c73c79eabdd
Revises: 0cb57e98042d
Create Date: 2021-03-03 23:22:39.253455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c73c79eabdd'
down_revision = '0cb57e98042d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('country', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'country')
    # ### end Alembic commands ###
